
server.port=8081
spring.application.name=pedidos-service
management.endpoints.web.exposure.include=health

url.estoque=${URL_ESTOQUE:http://localhost:8083}
url.pagamentos=${URL_PAGAMENTOS:http://localhost:8082}
